[package]
name = "sam-drawer-wasm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dot-writer = "0.1.4"
layout-rs = "0.1.3"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
